---
- name: Create directory
  become: yes
  file:
    path: /tmp/letsplay2
    state: directory
    mode: '0775'

- name: Install NFS
  become: yes
  apt:
    name: nfs-common
    state: present

- name: waiting for NFS server to be available
  become: yes
  wait_for:
    host: 192.168.50.12
    port: 2049
    timeout: 30
  changed_when: false

- name: Mount ComA NFS share
  become: yes
  ansible.posix.mount:
    path: /tmp/letsplay2
    src: "192.168.50.12:/tmp/letsplay"
    fstype: nfs
    opts: rw,nfsvers=4
    state: mounted
